//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace k1835web.Resources {
    using System;
    
    
    /// <summary>
    ///   Yerelleştirilmiş dizeleri aramak gibi işlemler için, türü kesin olarak belirtilmiş kaynak sınıfı.
    /// </summary>
    // Bu sınıf ResGen veya Visual Studio gibi bir araç kullanılarak StronglyTypedResourceBuilder
    // sınıfı tarafından otomatik olarak oluşturuldu.
    // Üye eklemek veya kaldırmak için .ResX dosyanızı düzenleyin ve sonra da ResGen
    // komutunu /str seçeneğiyle yeniden çalıştırın veya VS projenizi yeniden oluşturun.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Content {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Content() {
        }
        
        /// <summary>
        ///   Bu sınıf tarafından kullanılan, önbelleğe alınmış ResourceManager örneğini döndürür.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("k1835web.Resources.Content", typeof(Content).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Tümü için geçerli iş parçacığının CurrentUICulture özelliğini geçersiz kular
        ///   CurrentUICulture özelliğini tüm kaynak aramaları için geçersiz kılar.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   United we stand, diveded we fall. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string a24motto {
            get {
                return ResourceManager.GetString("a24motto", resourceCulture);
            }
        }
        
        /// <summary>
        ///    benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string a25text {
            get {
                return ResourceManager.GetString("a25text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   About Us benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string about {
            get {
                return ResourceManager.GetString("about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You don&apos;t have permission to access this property.  benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string accessDenied {
            get {
                return ResourceManager.GetString("accessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Active Season:  benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string activeSeasonText {
            get {
                return ResourceManager.GetString("activeSeasonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add Alliance benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string addAlliance {
            get {
                return ResourceManager.GetString("addAlliance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add Officer benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string addOfficer {
            get {
                return ResourceManager.GetString("addOfficer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add Season benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string addSeason {
            get {
                return ResourceManager.GetString("addSeason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Admin benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string admin {
            get {
                return ResourceManager.GetString("admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Admin Login Page benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string adminlogin {
            get {
                return ResourceManager.GetString("adminlogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Admin Panel benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string adminPanel {
            get {
                return ResourceManager.GetString("adminPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Alliance benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string alliance {
            get {
                return ResourceManager.GetString("alliance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Alliance Perfomances List  benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string allianceList {
            get {
                return ResourceManager.GetString("allianceList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Alliance Name benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string allianceName {
            get {
                return ResourceManager.GetString("allianceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There is already one alliance with the same name. Dublicated data is not accepted. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string alliMatch {
            get {
                return ResourceManager.GetString("alliMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Back to List benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string backToList {
            get {
                return ResourceManager.GetString("backToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   W&amp;R   /    War and Respect benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string box1 {
            get {
                return ResourceManager.GetString("box1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   S835  /  The Supreme Sodomites benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string box2 {
            get {
                return ResourceManager.GetString("box2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   35FF / The Fighting Farmers benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string box3 {
            get {
                return ResourceManager.GetString("box3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FK35 / French Kiss benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string box4 {
            get {
                return ResourceManager.GetString("box4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   AK35 / Ardrahan Knights benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string box5 {
            get {
                return ResourceManager.GetString("box5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TSSL / The Supreme Latinos benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string box6 {
            get {
                return ResourceManager.GetString("box6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Computer Scientist benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string compsci {
            get {
                return ResourceManager.GetString("compsci", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Contact benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string contact {
            get {
                return ResourceManager.GetString("contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Create benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string create {
            get {
                return ResourceManager.GetString("create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Player Registiration benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string createPlayer {
            get {
                return ResourceManager.GetString("createPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Database Operations benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string databaseOp {
            get {
                return ResourceManager.GetString("databaseOp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Database Error benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string dbError {
            get {
                return ResourceManager.GetString("dbError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The data you are trying to delete has childs on database. If you want to remove this data, you should delete the children first. (eq: Players or performances). benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string dbErrorTex {
            get {
                return ResourceManager.GetString("dbErrorTex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Deads benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string death {
            get {
                return ResourceManager.GetString("death", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Deaths Base benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string deathb {
            get {
                return ResourceManager.GetString("deathb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Deaths Last benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string deathl {
            get {
                return ResourceManager.GetString("deathl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Death Point benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string deathPercent {
            get {
                return ResourceManager.GetString("deathPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string delete {
            get {
                return ResourceManager.GetString("delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Performance Delete benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string deletePlayer {
            get {
                return ResourceManager.GetString("deletePlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Are you sure to delete this player? This process can not be taken back benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string deletePlayer2 {
            get {
                return ResourceManager.GetString("deletePlayer2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Are you sure to delete this object? This process can not be taken back. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string deleteText {
            get {
                return ResourceManager.GetString("deleteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Details benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string details {
            get {
                return ResourceManager.GetString("details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Edit benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string edit {
            get {
                return ResourceManager.GetString("edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Player Edit benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string editPlayer {
            get {
                return ResourceManager.GetString("editPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Nickname or Alliance can not be null. Please try again. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string emptyError {
            get {
                return ResourceManager.GetString("emptyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Rule Based Kingdom benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string hbox1 {
            get {
                return ResourceManager.GetString("hbox1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Are you always getting verbally abused? Having frequently civil wars? All you need is 1835. Our rules are set by council and applied to every player on the kingdom. If someone breaks the rules no matter his/her position, there will be punishments. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string hbox1t {
            get {
                return ResourceManager.GetString("hbox1t", resourceCulture);
            }
        }
        
        /// <summary>
        ///   International Kingdom benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string hbox2 {
            get {
                return ResourceManager.GetString("hbox2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Always lack of reinforcements during wars? Are you always fighting alone? These things are only in our imaginations in 1835. We are an highly active kingdom and we have players all around the world. You will never feel alone again! benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string hbox2t {
            get {
                return ResourceManager.GetString("hbox2t", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Efficient and Fiar Event System benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string hbox3 {
            get {
                return ResourceManager.GetString("hbox3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Does whales take all the events in your kingdom? Can&apos;t you grow? In 1835 mighthiest Governor Events and some of the 20 golden sculpture events are set for tier 4 players. We care about our tier 5 players, but we didn&apos;t abandon our brave tier 4 players too. We care for our infrastructure. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string hbox3t {
            get {
                return ResourceManager.GetString("hbox3t", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Brave and Experienced Players benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string hbox4 {
            get {
                return ResourceManager.GetString("hbox4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   We only accept fighters who showed their bravery.  benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string hbox4t {
            get {
                return ResourceManager.GetString("hbox4t", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Help benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string help {
            get {
                return ResourceManager.GetString("help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Home benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string home {
            get {
                return ResourceManager.GetString("home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Honor benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string honor {
            get {
                return ResourceManager.GetString("honor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Honor Base benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string honorb {
            get {
                return ResourceManager.GetString("honorb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Honor Last benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string honorl {
            get {
                return ResourceManager.GetString("honorl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Honor Point benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string honorPercent {
            get {
                return ResourceManager.GetString("honorPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Information benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string information {
            get {
                return ResourceManager.GetString("information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Is Active? benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string isActive {
            get {
                return ResourceManager.GetString("isActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kingdom Deaths Total:  benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string kdt {
            get {
                return ResourceManager.GetString("kdt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kingdom Honor Total:  benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string kht {
            get {
                return ResourceManager.GetString("kht", resourceCulture);
            }
        }
        
        /// <summary>
        ///   T4 Kill Point benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string killPercentt4 {
            get {
                return ResourceManager.GetString("killPercentt4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   T5 Kill Point benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string killPercentt5 {
            get {
                return ResourceManager.GetString("killPercentt5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kingdom benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string kingdom {
            get {
                return ResourceManager.GetString("kingdom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kingdom 1835 benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string kingdom1835 {
            get {
                return ResourceManager.GetString("kingdom1835", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kingdom Members benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string kingdomMembers {
            get {
                return ResourceManager.GetString("kingdomMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kingdom Resource Support Total:  benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string krsst {
            get {
                return ResourceManager.GetString("krsst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kingdom T4 Kills Total:  benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string kt4kt {
            get {
                return ResourceManager.GetString("kt4kt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kingdom T5 Kills Total:  benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string kt5kt {
            get {
                return ResourceManager.GetString("kt5kt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kvk Ranking benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string kvk {
            get {
                return ResourceManager.GetString("kvk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kvk Ranking benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string kvkRanking {
            get {
                return ResourceManager.GetString("kvkRanking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Landing Page benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string landingPage {
            get {
                return ResourceManager.GetString("landingPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Here are some reasons why you should join 1835 now! benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string lastbox {
            get {
                return ResourceManager.GetString("lastbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   About Our Kingdom benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string lastboxs {
            get {
                return ResourceManager.GetString("lastboxs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Alliance List / Edit benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string listEditAlliance {
            get {
                return ResourceManager.GetString("listEditAlliance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Officers List / Edit benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string listEditOfficers {
            get {
                return ResourceManager.GetString("listEditOfficers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Performances List / Edit benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string listEditPerformances {
            get {
                return ResourceManager.GetString("listEditPerformances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Players List / Edit benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string listEditPlayers {
            get {
                return ResourceManager.GetString("listEditPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Season List / Edit benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string listEditSeason {
            get {
                return ResourceManager.GetString("listEditSeason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Login benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string login {
            get {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Logout benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string logout {
            get {
                return ResourceManager.GetString("logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Management panel benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string managementPanel {
            get {
                return ResourceManager.GetString("managementPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This username is already taken. Process can not continue. Please try again with a different username benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string matchedUsername {
            get {
                return ResourceManager.GetString("matchedUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   With the high activity and fair reward system, we are offering you a very happy kingdom. You will never feel alone in our kingdom. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string membox1 {
            get {
                return ResourceManager.GetString("membox1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Happy kingdom members. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string membox1s {
            get {
                return ResourceManager.GetString("membox1s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Our I.T. team works for you. We have our own website, and we are working applications for you. You can always track your points on our website whenever you want. Kvk rewards will be shared fairly according to our systems.  benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string membox2 {
            get {
                return ResourceManager.GetString("membox2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fair reward system. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string membox2s {
            get {
                return ResourceManager.GetString("membox2s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Our kingdom has players all around the world. Kingship is rotating between online officers. You will never have to wait to do something in 1835! benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string membox3 {
            get {
                return ResourceManager.GetString("membox3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   High activity. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string membox3s {
            get {
                return ResourceManager.GetString("membox3s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   With the strategic planning team and highly active r4 from all alliances, victory will be ours in every war! benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string membox4 {
            get {
                return ResourceManager.GetString("membox4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kvk winner. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string membox4s {
            get {
                return ResourceManager.GetString("membox4s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Welcome to Kingdom 1835.. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string motto {
            get {
                return ResourceManager.GetString("motto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Move! benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string move {
            get {
                return ResourceManager.GetString("move", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Nickname benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string nickname {
            get {
                return ResourceManager.GetString("nickname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No Active Season benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string noActiveSeason {
            get {
                return ResourceManager.GetString("noActiveSeason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Alliance can not be null. Please tell your superadmins to add alliances to the system database. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string noAlliance {
            get {
                return ResourceManager.GetString("noAlliance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   None benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string none {
            get {
                return ResourceManager.GetString("none", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No Preparation Season benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string noPreparation {
            get {
                return ResourceManager.GetString("noPreparation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Performance values can not be saved because there are no active season.  benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string noSeason {
            get {
                return ResourceManager.GetString("noSeason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Player saved successfuly but this season is deactivated. Archieved performance data can not be changed! benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string notEditable {
            get {
                return ResourceManager.GetString("notEditable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Officer benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string officer {
            get {
                return ResourceManager.GetString("officer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Officers benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string officers {
            get {
                return ResourceManager.GetString("officers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Openfield benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string openfield {
            get {
                return ResourceManager.GetString("openfield", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Password benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Alliance (in Performance) benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string performanceAlliance {
            get {
                return ResourceManager.GetString("performanceAlliance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Create Performance benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string performanceCreate {
            get {
                return ResourceManager.GetString("performanceCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Performance Table benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string performanceTable {
            get {
                return ResourceManager.GetString("performanceTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You can see player performances on this tab. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string performanceTableTex {
            get {
                return ResourceManager.GetString("performanceTableTex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You can create player performance to active season on this tab. !There should be an active season, otherwise create process can not be proceed. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string performanceText {
            get {
                return ResourceManager.GetString("performanceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Player benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string player {
            get {
                return ResourceManager.GetString("player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Players benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string players {
            get {
                return ResourceManager.GetString("players", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Total Points benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string points {
            get {
                return ResourceManager.GetString("points", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A season can not be set &quot;Preparation&quot; and &quot;Active&quot; at the same time. Please make sure you set Preparation or Active. NOT BOTH! benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string prepActive {
            get {
                return ResourceManager.GetString("prepActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Preperation benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string preparation {
            get {
                return ResourceManager.GetString("preparation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Rally/Garrison benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string rallyandgarrison {
            get {
                return ResourceManager.GetString("rallyandgarrison", resourceCulture);
            }
        }
        
        /// <summary>
        ///   NO SWEARING benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string rbox1 {
            get {
                return ResourceManager.GetString("rbox1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Abusing others verbally is completely blocked in our kingdom. You need to respect to everyone, even your enemies. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string rbox1t {
            get {
                return ResourceManager.GetString("rbox1t", resourceCulture);
            }
        }
        
        /// <summary>
        ///   NO RACISM benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string rbox2 {
            get {
                return ResourceManager.GetString("rbox2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Racism is completely blocked in our kingdom. You need to respect to everyone, even your enemies. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string rbox2t {
            get {
                return ResourceManager.GetString("rbox2t", resourceCulture);
            }
        }
        
        /// <summary>
        ///   NO CITY ATTACKS benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string rbox3 {
            get {
                return ResourceManager.GetString("rbox3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kingdom players can not attack other cities unless the council order. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string rbox3t {
            get {
                return ResourceManager.GetString("rbox3t", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FOLLOWING MGE RULES benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string rbox4 {
            get {
                return ResourceManager.GetString("rbox4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Council sends mighthiest governor event rules before the event starts.  benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string rbox4t {
            get {
                return ResourceManager.GetString("rbox4t", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EVENT RULES benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string rbox5 {
            get {
                return ResourceManager.GetString("rbox5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Council sends specific event rules before the event starts. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string rbox5t {
            get {
                return ResourceManager.GetString("rbox5t", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DISCORD IS REQUIRED benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string rbox6 {
            get {
                return ResourceManager.GetString("rbox6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kingdom players should use discord. The best weapon on wars is communication. And we are using this weapon efficiently. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string rbox6t {
            get {
                return ResourceManager.GetString("rbox6t", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Register Members benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string registerMembers {
            get {
                return ResourceManager.GetString("registerMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Role benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string role {
            get {
                return ResourceManager.GetString("role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   RSS benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string rss {
            get {
                return ResourceManager.GetString("rss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   RSS Base benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string rssb {
            get {
                return ResourceManager.GetString("rssb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   RSS Last benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string rssl {
            get {
                return ResourceManager.GetString("rssl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Resources Point benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string rssPercent {
            get {
                return ResourceManager.GetString("rssPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Rules benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string rules {
            get {
                return ResourceManager.GetString("rules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save to Season benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string saveToSeason {
            get {
                return ResourceManager.GetString("saveToSeason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Season benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Season {
            get {
                return ResourceManager.GetString("Season", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There is already one season with the same name. Dublicated data is not accepted. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string seasonMatch {
            get {
                return ResourceManager.GetString("seasonMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Season Name benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string seasonName {
            get {
                return ResourceManager.GetString("seasonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There was an unknown error. Please report to the I.T. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string serverError {
            get {
                return ResourceManager.GetString("serverError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Where the legends are born! benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string slogan {
            get {
                return ResourceManager.GetString("slogan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Submit benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string submit {
            get {
                return ResourceManager.GetString("submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Process successful. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string success_db {
            get {
                return ResourceManager.GetString("success_db", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Super Admin benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string superadmin {
            get {
                return ResourceManager.GetString("superadmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   T4 Kills benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string t4k {
            get {
                return ResourceManager.GetString("t4k", resourceCulture);
            }
        }
        
        /// <summary>
        ///   T4 Kills Base benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string t4kb {
            get {
                return ResourceManager.GetString("t4kb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   T4 Kills Last benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string t4kl {
            get {
                return ResourceManager.GetString("t4kl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   T5 Kills benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string t5k {
            get {
                return ResourceManager.GetString("t5k", resourceCulture);
            }
        }
        
        /// <summary>
        ///   T5 Kills Base benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string t5kb {
            get {
                return ResourceManager.GetString("t5kb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   T5 Kills Last benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string t5kl {
            get {
                return ResourceManager.GetString("t5kl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Table benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string table {
            get {
                return ResourceManager.GetString("table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Every players records are stored in the database (t4 kills, t5 kills, deaths, rss support, honor points). 1). System calculates the total values. After that system calculates how much you contributed to these values. For example: (x*100)/total, where x is your t4 kills and total is the kingdom t4 kills. The result will show how much you contributed on %100. The last step is multiplying your % with the kvk season point. These points are set by the king. For example let&apos;s say your (x*100)/total is 24% for t4  [dizenin kalan bölümü kesildi]&quot;; benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string tableAciklama {
            get {
                return ResourceManager.GetString("tableAciklama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Every players records are stored in the database (t4 kills, t5 kills, deaths, rss support, honor points). 1). System calculates the total values. After that system calculates how much you contributed to these values. For example: (x*100)/total, where x is your t4 kills and total is the kingdom t4 kills. The result will show how much you contributed on %100. The last step is multiplying your % with the kvk season point. These points are set by the king. For example let&apos;s say your (x*100)/total is 24% for t4  [dizenin kalan bölümü kesildi]&quot;; benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string tableExp {
            get {
                return ResourceManager.GetString("tableExp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Team benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string team {
            get {
                return ResourceManager.GetString("team", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Player Type benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string type {
            get {
                return ResourceManager.GetString("type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Performance values should be number. Please try again. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string typeError {
            get {
                return ResourceManager.GetString("typeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Username benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string username {
            get {
                return ResourceManager.GetString("username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Welcome benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string welcome {
            get {
                return ResourceManager.GetString("welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Wipe Alliance benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string wipeAlliance {
            get {
                return ResourceManager.GetString("wipeAlliance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This process will wipe all the data belonging to the object you want to delete. This process can&apos;t be taken back. Are you sure to wipe the data? benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string wipeMessage {
            get {
                return ResourceManager.GetString("wipeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Wipe Season benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string WipeSeason {
            get {
                return ResourceManager.GetString("WipeSeason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cautious! benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string wipeWarning {
            get {
                return ResourceManager.GetString("wipeWarning", resourceCulture);
            }
        }
    }
}
